In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
array=np.array((1,2,3,4,5))
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#0 D Boyutlu Numpy Dizileri
import numpy as np
array=np.array(42)
print(array)
print(type(array))

42
<class 'numpy.ndarray'>


In [6]:
#1d boyutlu numpy dizileri od boyutlu numpy dizilerini kapsar
import numpy as np
array=np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#2d boyutlu diziler 1d boyutlu dizilerden oluşur.Genellikle matrisleri ve 2 boyutlu tensörleri ifade eder.




In [7]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
type(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [8]:
#3D diziler
import numpy as np
array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
import numpy as np
array1=np.array(42)
array2=np.array([1,2,3,4,5])
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
array4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)
print(f"{array1} numpy dizisinin boyutu:{array1.ndim}")
print(f"{array2} numpy dizisinin boyutu:{array2.ndim}")
print(f"{array3} numpy dizisinin boyutu:{array3.ndim}")
print(f"{array4} numpy dizisinin boyutu:{array4.ndim}")






0
1
2
3
42 numpy dizisinin boyutu:0
[1 2 3 4 5] numpy dizisinin boyutu:1
[[1 2 3]
 [4 5 6]
 [7 8 9]] numpy dizisinin boyutu:2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] numpy dizisinin boyutu:3


In [10]:
import numpy as np
array1=np.array(42)
array2=np.array([1,2,3,4,5])
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])
array4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array1.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)





()
(5,)
(3, 3)
(2, 2, 3)


In [11]:
#nboyutlu dızı
array=np.array([1,2,3,4,5],ndmin=5)

print(array)

[[[[[1 2 3 4 5]]]]]


In [12]:
array=np.array([[1,2,3],[4,5,6]])
print(f"1.satırda bulunan ikinci eleman: {array[0,1]}" )

1.satırda bulunan ikinci eleman: 2


In [13]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array[0:3,0:2])
print(array[0:1,2])

[[1 2]
 [6 7]]
[3]


In [14]:
array=np.array([1,2,3,4])
array.dtype

dtype('int64')

In [15]:
import numpy as np
array=np.array([1,2,"elma"])
array.dtype
print(array)

['1' '2' 'elma']


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[1]=45
print(x)
print(arr)

[ 1 45  3  4  5]
[ 1 45  3  4  5]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()    #kopya olusturma ıslemı
arr[2]=9
print(x)
print(arr)

[1 2 3 4 5]
[1 2 9 4 5]


In [18]:
array=np.array([[1,2,3],[5,67,8]])
array.shape #boyutunu belırtır

(2, 3)

In [19]:
array=np.array([1,2,3,4,6,7,8,9])
newarray=array.reshape(2,4)
newarray  #Verdıgım degerlerden yenı bır array olusturuyor
#print(newarray)


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [20]:
arr=np.array([[1,2,3,4,],[6,7,8,9]])
newarr=arr.reshape(-1)
newarr

array([1, 2, 3, 4, 6, 7, 8, 9])

In [21]:
#dizilerde iterasyon
array=np.array([[1,2,3,4,5],[22,66,55,12,33]])
for x in array:
    print(x)

[1 2 3 4 5]
[22 66 55 12 33]


In [22]:
array=np.array([[1,2,3,4,5],[22,66,55,12,33]])
for x in array:
    for y in x:
        print(y)

1
2
3
4
5
22
66
55
12
33


In [23]:
array=np.array([[1,2,3,4,5],[22,66,55,12,33]])
for x in np.nditer(array):  #tamamını yazdırır
 print(x)

1
2
3
4
5
22
66
55
12
33


In [24]:
array=np.array([[1,2,3,4,5],[22,66,55,12,33]])
for idx, item in np.ndenumerate(array):
    print(idx,item)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 22
(1, 1) 66
(1, 2) 55
(1, 3) 12
(1, 4) 33


In [25]:
#numpy dizilerini birleştirme
arr1=np.array([1,2,3,45])
arr2=np.array([55,4,1,2])
arrayc=np.concatenate((arr1,arr2))
arrayc

array([ 1,  2,  3, 45, 55,  4,  1,  2])

In [26]:
arr1=np.array([[1,2],[3,45]])
arr2=np.array([[55,4],[1,2]])
arrayc=np.concatenate((arr1,arr2),axis=1)
print(arrayc)
arrayc2=np.concatenate((arr1,arr2),axis=0)
arrayc2

[[ 1  2 55  4]
 [ 3 45  1  2]]


array([[ 1,  2],
       [ 3, 45],
       [55,  4],
       [ 1,  2]])

In [27]:
array=np.array([[1,2,3,4,5],[22,66,55,12,33]])
x=np.where(array==66)
x

(array([1]), array([1]))

In [28]:
array=np.array([1,2,3,4,6,7,8,9,27,12,45,99])
np.sort(array)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 12, 27, 45, 99])

In [29]:
array=np.array(["h","a","c","d","g",1])
np.sort(array)

array(['1', 'a', 'c', 'd', 'g', 'h'], dtype='<U21')

In [30]:
array=np.array([1,2,3,4,5])
x=[True,False,True,False,True]
array[x]

array([1, 3, 5])

In [31]:
array=np.array([11,55,48,56,1,2,45,78,989,87,197,9754,])
array<12

array([ True, False, False, False,  True,  True, False, False, False,
       False, False, False])

In [32]:
#numpy rastgele sayılar
array=np.random.randint(33,size=44)
array

array([11,  4,  8, 10, 26, 16, 29, 19, 25, 27,  0, 22,  7, 11, 32,  8,  4,
       31, 28,  9, 15,  4,  8, 28, 25, 28,  3, 12, 31, 32, 11, 24, 28, 29,
       19, 26, 15,  2, 25, 22,  7,  6, 12, 31])

In [33]:
array=np.random.randint(33,size=(5,5))
array

array([[ 9,  1, 21, 18, 15],
       [14, 13, 23, 16, 12],
       [20, 20,  4,  0,  8],
       [ 8,  5,  9,  3,  9],
       [32, 30, 10, 13,  0]])